

services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dialDB
    ports:
      - '8886:3306'
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8899:80'
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - '9000:9000'
    depends_on:
      - db

volumes:
  dbdata:
