
services:
  nestjs:
    image: dial-me
    container_name: nestjs
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dialDB
    ports:
      - '8886:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - '8899:80'
