services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dialDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: ^1Wr04yB!NF8
    restart: always
    ports:
      - '8886:3306'
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8899:80'

volumes:
  dbdata:
