version: '3.8'
services:
  app:
    image: dial-me:latest
    ports:
      - "9001:9000"
    depends_on:
      - db
    environment:
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_PHONE_NUMBER

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dialDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: '^1Wr04yB!NF8'
    ports:
      - "8886:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8899:80'
volumes:
  dbdata:
